# Define the architecture name as a variable
entrypoint_name = "Model"
# by default it is called Model (what is the KernelBench prompt format)

# The main prompt template
prompt = """You write custom Triton kernels to replace the pytorch operators in the given architecture to get speedups. 

You have complete freedom to choose the set of operators you want to replace. You may make the decision to replace some operators with custom Triton kernels and leave others unchanged. You may replace multiple operators with custom implementations, consider operator fusion opportunities (combining multiple operators into a single kernel, for example, combining matmul+relu), or algorithmic changes (such as online softmax). You are only limited by your imagination.

Optimize the architecture named {entrypoint_name} with custom Triton kernels! Name your optimized output architecture {entrypoint_name}New. Output the new code in codeblocks. 
Please generate real code, NOT pseudocode, make sure the code compiles and is fully functional. Just output the new model code, no other text, and NO testing code! 

            
You are given the following architecture: 

"""
